--1.Создать таблицу employees
create table employees(
	id serial primary key,
	employee_name varchar(50) not null
);

--2.Наполнить таблицу employee 70 строками.
insert into employees(employee_name)
values('Stanley'),
	  ('Tadeo'),
      ('Wayne'),
	  ('Harrison'),
	  ('Vander'),
	  ('Pete'),
	  ('Adriel'),
	  ('Hugh'),
	  ('Darren'),
	  ('River'),
	  ('Fabian'),
	  ('Perseus'),
	  ('Armando'),
	  ('Kaleb'),
	  ('William'),
	  ('Yasir'),
	  ('Jeremiah'),
	  ('Sebastian'),
	  ('Phillip'),
	  ('Miles'),
	  ('Zaine'),
	  ('Xandros'),
	  ('Ezequiel'),
	  ('Holden'),
	  ('William'),
	  ('Uzziah'),
	  ('Leonidas'),
      ('Uday'),
	  ('Mario'),
	  ('Jaxson'),
	  ('Anderson'),
	  ('Valente'),
	  ('Sebastian'),
	  ('Virginius'),
	  ('Zev'),
	  ('Malachi'),
	  ('Phineas'),
	  ('Yoshinobu'),
	  ('Wylie'),
	  ('Xuan'),
	  ('Israel'),
	  ('Oren'),
	  ('Umar'),
	  ('Dominick'),
	  ('Jameson'),
	  ('Kane'),
	  ('Osvaldo'),
	  ('Thaddeus'),
	  ('Ace'),
	  ('Killian'),
	  ('Natan'),
	  ('Zeus'),
	  ('Barrett'),
	  ('Yanni'),
	  ('Dawson'),
	  ('Emery'),
	  ('Iver'),
	  ('Izaiah'),
	  ('Mohamed'),
	  ('Roberto'),
	  ('Marcus'),
	  ('London'),
	  ('Quirino'),
	  ('Issac'),
	  ('Eric'),
	  ('Isaiah'),
	  ('Yosef'),
	  ('Nathaniel'),
	  ('Xavier'),
	  ('Uria');

--3.Создать таблицу salary
create table salary1(
	id serial primary key,
	monthly_salary1 int not null
); 

--4.Наполнить таблицу salary 15 строками:
insert into salary1(monthly_salary1)
values(1000),
	  (1100),
	  (1200),
	  (1300),
	  (1400),
	  (1500),
	  (1600),
	  (1700),
	  (1800),
	  (1900),
	  (2000),
	  (2100),
	  (2200),
	  (2300),
	  (2400),
	  (2500);

--5.Создать таблицу employee_salary
create table employee_salary(
	id serial primary key,
	employee_id int not null,
	salary_id int not null,
	foreign key(employee_id)
		references employees(id),
	foreign key(salary_id)
		references salary1(id)
);

--6.Наполнить таблицу employee_salary 40 строками:
-- в 10 строк из 40 вставить несуществующие employee_id
insert into employee_salary(employee_id,salary_id)
values(3, 7),
      (1, 4),
      (5, 9),
      (40, 13),
      (23, 4),
      (11, 2),
      (52, 10),
      (15, 14),
      (26, 16),
      (16, 1),
      (33, 7),
      (2, 4),
      (4, 7),
      (41, 3),
      (43, 5),
      (21, 5),
      (39, 14),
      (17, 12),
      (36, 11),
      (13, 10),
      (37, 9),
      (42, 4),
      (43, 6),
      (41, 14),
      (39, 11),
      (61, 15),
      (63, 12),
      (71, 3),
      (73, 7),
      (81, 4),
      (113, 7),
      (111, 4),
      (113, 7),
      (91, 4),
      (87, 7),
      (77, 4),
      (75, 7),
      (74, 4),
      (73, 7),
      (71, 4),

	 select * from employee_salary ;
